//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnLocationEVMT {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AllResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AllResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnLocationEVMT.AllResource", typeof(AllResource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want delete this..
        /// </summary>
        internal static string AreSure {
            get {
                return ResourceManager.GetString("AreSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        internal static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01/01/1900.
        /// </summary>
        internal static string BlankDate {
            get {
                return ResourceManager.GetString("BlankDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to view this page..
        /// </summary>
        internal static string BoothCardPermission {
            get {
                return ResourceManager.GetString("BoothCardPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://mstage.onlocationind.com/sites/services/_vti_bin/OliMobile/OliService.svc/GetBoothcardSummary.
        /// </summary>
        internal static string BoothSignatureURL {
            get {
                return ResourceManager.GetString("BoothSignatureURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #72D54A.
        /// </summary>
        internal static string ColorCode {
            get {
                return ResourceManager.GetString("ColorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        internal static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials. Please try again..
        /// </summary>
        internal static string InvalidUser {
            get {
                return ResourceManager.GetString("InvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetYourProjectList.
        /// </summary>
        internal static string MethodGetpProject {
            get {
                return ResourceManager.GetString("MethodGetpProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetYourProjectTeam.
        /// </summary>
        internal static string MethodGetYourTeam {
            get {
                return ResourceManager.GetString("MethodGetYourTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minus.
        /// </summary>
        internal static string Minus {
            get {
                return ResourceManager.GetString("Minus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter username and password..
        /// </summary>
        internal static string NameAndPassword {
            get {
                return ResourceManager.GetString("NameAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Error.
        /// </summary>
        internal static string NetworkAlert {
            get {
                return ResourceManager.GetString("NetworkAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Connectivity, Internet might not be connected..
        /// </summary>
        internal static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Record Found..
        /// </summary>
        internal static string NoRecord {
            get {
                return ResourceManager.GetString("NoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://mstage.onlocationind.com/sites/services/_vti_bin/OliMobile/OliService.svc/PutOliData.
        /// </summary>
        internal static string OperationURL {
            get {
                return ResourceManager.GetString("OperationURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoothCards.
        /// </summary>
        internal static string PageTypeBoothCards {
            get {
                return ResourceManager.GetString("PageTypeBoothCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pic.
        /// </summary>
        internal static string PageTypePic {
            get {
                return ResourceManager.GetString("PageTypePic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string PageTypeProject {
            get {
                return ResourceManager.GetString("PageTypeProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        internal static string PageTypeTeam {
            get {
                return ResourceManager.GetString("PageTypeTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoothcardSummary.pdf.
        /// </summary>
        internal static string PDFName {
            get {
                return ResourceManager.GetString("PDFName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        internal static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnLocation need storage permission..
        /// </summary>
        internal static string PermissionMessgae {
            get {
                return ResourceManager.GetString("PermissionMessgae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions Required..
        /// </summary>
        internal static string PermissionsRequired {
            get {
                return ResourceManager.GetString("PermissionsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plus.
        /// </summary>
        internal static string Plus {
            get {
                return ResourceManager.GetString("Plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while processing your request. Please try again..
        /// </summary>
        internal static string ProcessingRequest {
            get {
                return ResourceManager.GetString("ProcessingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while retreiving data from server. Please try again..
        /// </summary>
        internal static string RequestError {
            get {
                return ResourceManager.GetString("RequestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Save Successfully..
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://mstage.onlocationind.com/sites/services/_vti_bin/OliMobile/OliService.svc/OliDetails.
        /// </summary>
        internal static string ServiceURL {
            get {
                return ResourceManager.GetString("ServiceURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Signature here..
        /// </summary>
        internal static string SignMessage {
            get {
                return ResourceManager.GetString("SignMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://exhibition-directory.c14.ixsecure.com/onlocation_m/index.php.
        /// </summary>
        internal static string TradeShowURL {
            get {
                return ResourceManager.GetString("TradeShowURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
