//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnLocationEVMT {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnLocationEVMT.Resource", typeof(Resource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddNew.
        /// </summary>
        internal static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        internal static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01/01/1900.
        /// </summary>
        internal static string BlankDate {
            get {
                return ResourceManager.GetString("BlankDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to view this page..
        /// </summary>
        internal static string BoothCardPermission {
            get {
                return ResourceManager.GetString("BoothCardPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booth Size.
        /// </summary>
        internal static string BoothSize {
            get {
                return ResourceManager.GetString("BoothSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://mstage.onlocationind.com/sites/services/_vti_bin/OliMobile/OliService.svc/GetBoothcardSummary.
        /// </summary>
        internal static string BoothSummaryURL {
            get {
                return ResourceManager.GetString("BoothSummaryURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to check.png.
        /// </summary>
        internal static string checkImage {
            get {
                return ResourceManager.GetString("checkImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://onlocationind.com/city-guides/chicago.pdf.
        /// </summary>
        internal static string ChicagoPDF {
            get {
                return ResourceManager.GetString("ChicagoPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        internal static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #72D54A.
        /// </summary>
        internal static string ColorCode {
            get {
                return ResourceManager.GetString("ColorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want delete this?.
        /// </summary>
        internal static string ConfirmationMessage {
            get {
                return ResourceManager.GetString("ConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM/dd/yyyy.
        /// </summary>
        internal static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd.
        /// </summary>
        internal static string DateFormatOpp {
            get {
                return ResourceManager.GetString("DateFormatOpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM/dd/yyyy hh:mm tt.
        /// </summary>
        internal static string DateFormatWithTime {
            get {
                return ResourceManager.GetString("DateFormatWithTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date should be greater than Start Date..
        /// </summary>
        internal static string DateValidMessage {
            get {
                return ResourceManager.GetString("DateValidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12:00 AM.
        /// </summary>
        internal static string DefaultTimeFormat {
            get {
                return ResourceManager.GetString("DefaultTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Record Deleted Successfully.
        /// </summary>
        internal static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismantle.
        /// </summary>
        internal static string Dismantle {
            get {
                return ResourceManager.GetString("Dismantle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Hour.
        /// </summary>
        internal static string EndHour {
            get {
                return ResourceManager.GetString("EndHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Minute.
        /// </summary>
        internal static string EndMinute {
            get {
                return ResourceManager.GetString("EndMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid job number..
        /// </summary>
        internal static string EnterJob {
            get {
                return ResourceManager.GetString("EnterJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Note..
        /// </summary>
        internal static string EnterNote {
            get {
                return ResourceManager.GetString("EnterNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter search keywords..
        /// </summary>
        internal static string EnterSearchKeywords {
            get {
                return ResourceManager.GetString("EnterSearchKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        internal static string Equipment {
            get {
                return ResourceManager.GetString("Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Quantity.
        /// </summary>
        internal static string EquipmentQuantity {
            get {
                return ResourceManager.GetString("EquipmentQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exhibit House.
        /// </summary>
        internal static string ExhibitHouse {
            get {
                return ResourceManager.GetString("ExhibitHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FilterIcon.png.
        /// </summary>
        internal static string FilterIcon {
            get {
                return ResourceManager.GetString("FilterIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #71D64A.
        /// </summary>
        internal static string GreenHex {
            get {
                return ResourceManager.GetString("GreenHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Record Insert/Update Successfully..
        /// </summary>
        internal static string InsertUpdateSuccess {
            get {
                return ResourceManager.GetString("InsertUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Location (Internal Use).
        /// </summary>
        internal static string InternalUse {
            get {
                return ResourceManager.GetString("InternalUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        internal static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials. Please try again..
        /// </summary>
        internal static string InvalidUser {
            get {
                return ResourceManager.GetString("InvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://mstage.onlocationind.com/sites/services/_vti_bin/OliMobile/OliService.svc/.
        /// </summary>
        internal static string InvoiceURL {
            get {
                return ResourceManager.GetString("InvoiceURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsBusy.
        /// </summary>
        internal static string IsBusy {
            get {
                return ResourceManager.GetString("IsBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://onlocationind.com/city-guides/las-vegas.pdf.
        /// </summary>
        internal static string LasPDF {
            get {
                return ResourceManager.GetString("LasPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaterialsExtras.
        /// </summary>
        internal static string MaterialsExtras {
            get {
                return ResourceManager.GetString("MaterialsExtras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Used.
        /// </summary>
        internal static string MaterialUsed {
            get {
                return ResourceManager.GetString("MaterialUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetEstDetails_InstallDismantle.
        /// </summary>
        internal static string MethodGetEstDetailsInstallDismantle {
            get {
                return ResourceManager.GetString("MethodGetEstDetailsInstallDismantle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetEstDetails_MaterialsExtras.
        /// </summary>
        internal static string MethodGetEstDetailsMaterialsExtras {
            get {
                return ResourceManager.GetString("MethodGetEstDetailsMaterialsExtras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetEstDetails_ShowServices.
        /// </summary>
        internal static string MethodGetEstDetailsShowServices {
            get {
                return ResourceManager.GetString("MethodGetEstDetailsShowServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetEstimateSummary.
        /// </summary>
        internal static string MethodGetEstimateSummary {
            get {
                return ResourceManager.GetString("MethodGetEstimateSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetYourProjectList.
        /// </summary>
        internal static string MethodGetpProject {
            get {
                return ResourceManager.GetString("MethodGetpProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetProjectDetails.
        /// </summary>
        internal static string MethodGetProjectDetails {
            get {
                return ResourceManager.GetString("MethodGetProjectDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetProjectStaff.
        /// </summary>
        internal static string MethodGetProjectStaff {
            get {
                return ResourceManager.GetString("MethodGetProjectStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetUserType.
        /// </summary>
        internal static string MethodGetUserType {
            get {
                return ResourceManager.GetString("MethodGetUserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetYourProjectTeam.
        /// </summary>
        internal static string MethodGetYourTeam {
            get {
                return ResourceManager.GetString("MethodGetYourTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InsertBoothHeaderData.
        /// </summary>
        internal static string MethodInsertBoothHeaderData {
            get {
                return ResourceManager.GetString("MethodInsertBoothHeaderData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PutBoothLaborDetails.
        /// </summary>
        internal static string MethodPutBoothLaborDetails {
            get {
                return ResourceManager.GetString("MethodPutBoothLaborDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateBoothHeaderData.
        /// </summary>
        internal static string MethodUpdateBoothHeaderData {
            get {
                return ResourceManager.GetString("MethodUpdateBoothHeaderData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minus.
        /// </summary>
        internal static string Minus {
            get {
                return ResourceManager.GetString("Minus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NA.
        /// </summary>
        internal static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter username and password..
        /// </summary>
        internal static string NameAndPassword {
            get {
                return ResourceManager.GetString("NameAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #NA.
        /// </summary>
        internal static string NAWithHash {
            get {
                return ResourceManager.GetString("NAWithHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Error.
        /// </summary>
        internal static string NetworkAlert {
            get {
                return ResourceManager.GetString("NetworkAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Connectivity, Internet might not be connected..
        /// </summary>
        internal static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update is available with new feature, bug fixes and many more..
        /// </summary>
        internal static string NewUpdateMessage {
            get {
                return ResourceManager.GetString("NewUpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Record Found..
        /// </summary>
        internal static string NoRecord {
            get {
                return ResourceManager.GetString("NoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Not Found..
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://onlocationind.com/city-guides/nyc.pdf.
        /// </summary>
        internal static string NYCPDF {
            get {
                return ResourceManager.GetString("NYCPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Location.
        /// </summary>
        internal static string OnLocation {
            get {
                return ResourceManager.GetString("OnLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://onlocationind.com/city-guides/orlando.pdf.
        /// </summary>
        internal static string OrlandoPDF {
            get {
                return ResourceManager.GetString("OrlandoPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoothCards.
        /// </summary>
        internal static string PageTypeBoothCards {
            get {
                return ResourceManager.GetString("PageTypeBoothCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pic.
        /// </summary>
        internal static string PageTypePic {
            get {
                return ResourceManager.GetString("PageTypePic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string PageTypeProject {
            get {
                return ResourceManager.GetString("PageTypeProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        internal static string PageTypeTeam {
            get {
                return ResourceManager.GetString("PageTypeTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoothcardSummary.pdf.
        /// </summary>
        internal static string PDFName {
            get {
                return ResourceManager.GetString("PDFName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        internal static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnLocation need storage permission..
        /// </summary>
        internal static string PermissionMessgae {
            get {
                return ResourceManager.GetString("PermissionMessgae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions Required..
        /// </summary>
        internal static string PermissionsRequired {
            get {
                return ResourceManager.GetString("PermissionsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://onlocationind.com/city-guides/philadelphia.pdf.
        /// </summary>
        internal static string PhiladephiaPDF {
            get {
                return ResourceManager.GetString("PhiladephiaPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter.
        /// </summary>
        internal static string Pleaseenter {
            get {
                return ResourceManager.GetString("Pleaseenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plus.
        /// </summary>
        internal static string Plus {
            get {
                return ResourceManager.GetString("Plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while processing your request. Please try again..
        /// </summary>
        internal static string ProcessingRequest {
            get {
                return ResourceManager.GetString("ProcessingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rdchecked.png.
        /// </summary>
        internal static string RdChecked {
            get {
                return ResourceManager.GetString("RdChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rdunchecked.png.
        /// </summary>
        internal static string RdUnChecked {
            get {
                return ResourceManager.GetString("RdUnChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while retreiving data from server. Please try again..
        /// </summary>
        internal static string RequestError {
            get {
                return ResourceManager.GetString("RequestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResetIcon.png.
        /// </summary>
        internal static string ResetIcon {
            get {
                return ResourceManager.GetString("ResetIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Save Successfully..
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveAll.
        /// </summary>
        internal static string SaveAll {
            get {
                return ResourceManager.GetString("SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Record Save Successfully..
        /// </summary>
        internal static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchIcon.png.
        /// </summary>
        internal static string SearchIcon {
            get {
                return ResourceManager.GetString("SearchIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Employee.
        /// </summary>
        internal static string SelectEmployee {
            get {
                return ResourceManager.GetString("SelectEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Task.
        /// </summary>
        internal static string SelectTask {
            get {
                return ResourceManager.GetString("SelectTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://mstage.onlocationind.com/sites/services/_vti_bin/OliMobile/OliService.svc/.
        /// </summary>
        internal static string ServiceURL {
            get {
                return ResourceManager.GetString("ServiceURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowServices.
        /// </summary>
        internal static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Services.
        /// </summary>
        internal static string ShowServices {
            get {
                return ResourceManager.GetString("ShowServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Signature here..
        /// </summary>
        internal static string SignHere {
            get {
                return ResourceManager.GetString("SignHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Signature here..
        /// </summary>
        internal static string SignMessage {
            get {
                return ResourceManager.GetString("SignMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Hour.
        /// </summary>
        internal static string StartHours {
            get {
                return ResourceManager.GetString("StartHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Minute.
        /// </summary>
        internal static string StartMinute {
            get {
                return ResourceManager.GetString("StartMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0200.
        /// </summary>
        internal static string TaskDismantle {
            get {
                return ResourceManager.GetString("TaskDismantle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0100.
        /// </summary>
        internal static string TaskInstall {
            get {
                return ResourceManager.GetString("TaskInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0150.
        /// </summary>
        internal static string TaskService {
            get {
                return ResourceManager.GetString("TaskService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0700.
        /// </summary>
        internal static string TaskTravel {
            get {
                return ResourceManager.GetString("TaskTravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1200.
        /// </summary>
        internal static string TaskWarehouse {
            get {
                return ResourceManager.GetString("TaskWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hh:mm tt.
        /// </summary>
        internal static string TimeFormat {
            get {
                return ResourceManager.GetString("TimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://thetradeshowcalendar.com/onlocation_m/index.php?BNR=&amp;vCtry=United+States.
        /// </summary>
        internal static string TradeShowURL {
            get {
                return ResourceManager.GetString("TradeShowURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Of Measure.
        /// </summary>
        internal static string UnitOfMeasure {
            get {
                return ResourceManager.GetString("UnitOfMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Time.
        /// </summary>
        internal static string ValidDT {
            get {
                return ResourceManager.GetString("ValidDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        internal static string ValidEmployee {
            get {
                return ResourceManager.GetString("ValidEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Time.
        /// </summary>
        internal static string ValidLT {
            get {
                return ResourceManager.GetString("ValidLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over Time.
        /// </summary>
        internal static string ValidOT {
            get {
                return ResourceManager.GetString("ValidOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight Time.
        /// </summary>
        internal static string ValidST {
            get {
                return ResourceManager.GetString("ValidST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        internal static string ValidTask {
            get {
                return ResourceManager.GetString("ValidTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ffffff.
        /// </summary>
        internal static string WhiteHex {
            get {
                return ResourceManager.GetString("WhiteHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string Zero {
            get {
                return ResourceManager.GetString("Zero", resourceCulture);
            }
        }
    }
}
